name: Application Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0

    # PHP Syntax Check
    - name: Verify PHP Syntax
      run: |
        for file in $(find . -name "*.php"); do
          php -l $file;
        done

    # HTML Validation
    - name: Validate HTML
      run: |
        sudo apt-get install -y tidy
        for file in $(find . -name "*.html"); do
          tidy -e $file;
        done

    # CSS Validation
    - name: Validate CSS
      run: |
        sudo apt-get install -y nodejs npm
        npm install -g stylelint
        for file in $(find . -name "*.css"); do
          stylelint $file;
        done
