name: Application Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0 

    - name: Verify PHP Syntax
      run: php -l Index.php  
    
    - name: Validate HTML
      run: |
        sudo apt-get install -y tidy
        tidy -e *.html

    - name: Validate CSS
      run: |
        sudo apt-get install -y nodejs npm
        npm install -g stylelint
        stylelint '**/*.css'
    
